image: jujusolutions/charmbox
env:
    - JUJU_REPOSITORY='/var/cache/drone/src/github.com/chuckbutler/'
git:
    path: github.com/chuckbutler/kubes-juju-builder
script:
    - sudo apt-get update
    - juju init
    - echo $ENVYAML | base64 --decode > ~/.juju/environments.yaml
    - juju $$CIENV
    - ./kubes-ci-run.sh
