image: jujusolutions/charmbox
env:
    - JUJU_REPOSITORY='/var/cache/drone/src/github.com/chuckbutler/'
git:
    path: github.com/chuckbutler/kubes-juju-builder
script:
    - sudo apt-get update
    - juju init
    - echo $ENVYAML | base64 --decode > ~/.juju/environments.yaml
    - juju switch $$CIENV
    - echo $$CIENV > ~/.juju/current-environment
    - ./kubes-ci-run.sh
notify:
  slack:
    webhook_url: $SLACKHOOK
    username: 'drone'
    channel: '#dev'
    on_started: false
    on_success: true
    on_failure: true
